---

- hosts: zookeeper
  remote_user: vagrant
  become: yes
  roles:
    - zookeeper

- hosts: mesos-master
  remote_user: vagrant
  become: yes
  roles:
    - mesos
    - marathon

- hosts: mesos-slave
  remote_user: vagrant
  become: yes
  roles:
    - docker
    - mesos
