---

###
# SWARM
###

# Port
swarm_port: 2377

# Swarm Leader
swarm_leader: "{{ groups['swarm-master'][0] }}"
swarm_leader_address: "{{ hostvars[swarm_leader].ip }}:{{ swarm_port }}"

# Swarm listen address
swarm_listen_address: "{{ hostvars[ansible_hostname].ip }}:{{ swarm_port }}"
