.TH PORTUSCTL 1 "portusctl User manuals" "SUSE LLC." "AUGUST 2016"
.SH NAME
.PP
portusctl help \- Show a help message for the given command
.SH SYNOPSIS
.PP
\fBportusctl help\fP <command>
.SH DESCRIPTION
.PP
The \fBhelp\fP command shows a help message for the given command.
.SH HISTORY
.PP
August 2016, created by Miquel Sabaté Solà \[la]msabate@suse.com\[ra]
