.TH PORTUSCTL 1 "portusctl User manuals" "SUSE LLC." "AUGUST 2016"
.SH NAME
.PP
portusctl rake \- Execute rake commands available within Portus
.SH SYNOPSIS
.PP
\fBportusctl rake\fP <task> [arguments...]
.SH DESCRIPTION
.PP
The \fBrake\fP command allows administrators to execute rake tasks that are
available within the Portus context. Some of these tasks have been defined by
Portus developers, and some others are plain tasks defined by Ruby on Rails or
some other gem. In order to get the full list of all the available tasks,
execute:
.PP
.RS
.nf
$ portusctl rake \-T
.fi
.RE
.PP
It is not recommended to execute any rake task if you are not experienced with
Portus or you are on a production server.
.SH EXAMPLES
.PP
As shown in the description, "portusctl rake \-T" will give you the available
tasks. Moreover, as it's been also explained in the description section, these
tasks are advanced and should be used with caution. That being said, there is at
least one task that is really useful:
.PP
.RS
.nf
$ portusctl rake portus:info
.fi
.RE
.PP
The previous task will give you detailed output of:
.RS
.IP \(bu 2
The exact version of Portus that you are running.
.IP \(bu 2
The configuration being used (with sensible information hidden).
.RE
.PP
This task is really useful to give developers more information when fixing an
issue that you might be having.
.SH HISTORY
.PP
August 2016, created by Miquel Sabaté Solà \[la]msabate@suse.com\[ra]
