---

- name: DOCKER COMPOSE | Get current version
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false
  tags: update-docker-compose

- name: DOCKER COMPOSE | Uninstall current binary
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout
  tags: update-docker-compose

- name: DOCKER COMPOSE | Installation
  get_url:
    url: "{{ docker_compose_binary_url }}"
    dest: "{{ docker_compose_path }}"
    owner: root
    group: root
    mode: 0755
  tags: update-docker-compose
