---

- name: DOCKER | Manage Redhat environment
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: DOCKER | Manage Debian environment
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: DOCKER | Install
  package:
    name: "{{ docker_package | default('docker-ce') }}"
    state: present
  notify: Restart docker

- name: DOCKER | Ensure handlers are notified
  meta: flush_handlers

- name: DOCKER | Manage Docker Compose
  include_tasks: compose.yml
  tags: update-docker-compose

- name: DOCKER | Manage Docker users
  include_tasks: users.yml
  when: docker_users
  tags: update-docker-user

- name: DOCKER | Log to an existing account
  include_tasks: login.yml
  when: docker_login is defined and docker_login.username != ""
  tags: update-docker-login
