#!/bin/bash

## Install the registry
zypper ar -f http://download.opensuse.org/repositories/Virtualization:/containers/openSUSE_13.2 Virtualization:containers
zypper --gpg-auto-import-keys ref

zypper -n in docker-distribution-registry

systemctl enable registry
systemctl start registry
